$integration: 'http://ibm.com/appconnect/integration/v2/integrationFile'
integration:
  type: trigger-action
  trigger-interfaces:
    trigger-interface-1:
      connector-type: streaming-connector-scheduler
      type: event-trigger
      triggers:
        SCHEDULE:
          input-context:
            data: scheduler
          assembly:
            $ref: '#/integration/assemblies/assembly-1'
          options:
            subscription:
              scheduleConfiguration:
                interval:
                  unit: hour
                  value: 1
                  runOnceOncheck: true
                  days:
                    - MON
                    - TUE
                    - WED
                    - THU
                    - FRI
                    - SAT
                    - SUN
                  timeZone: UTC
  action-interfaces:
    action-interface-1:
      type: api-action
      business-object: Hash
      connector-type: rediscache
      actions:
        GETFIELDVALUE: {}
    action-interface-2:
      type: api-action
      business-object: message
      connector-type: slack
      actions:
        CREATE: {}
  assemblies:
    assembly-1:
      assembly:
        execute:
          - custom-action:
              name: Redis Get hash field value
              target:
                $ref: '#/integration/action-interfaces/action-interface-1'
              action: GETFIELDVALUE
              map:
                mappings:
                  - field:
                      template: name
                  - key:
                      template: SPHash
                $map: 'http://ibm.com/appconnect/map/v1'
                input:
                  - variable: Trigger
                    $ref: '#/trigger/payload'
          - create-action:
              name: Slack Create message
              target:
                $ref: '#/integration/action-interfaces/action-interface-2'
              map:
                mappings:
                  - channel:
                      template: CGBD6QR0B
                  - text:
                      template: '{{$RedisGethashfieldvalue}}'
                $map: 'http://ibm.com/appconnect/map/v1'
                input:
                  - variable: Trigger
                    $ref: '#/trigger/payload'
                  - variable: RedisGethashfieldvalue
                    $ref: '#/node-output/Redis Get hash field value/response/payload'
  name: Retrieve a configuration string from Redis
models: {}
